### PR TITLE
feat: add ERC20 contract and tests

### LINKED ISSUE #26: Create a basic ERC20 contract
## Description
- As part of the examples, we aim to include an ERC20 contract to explore its structure and gain a fundamental understanding of token standards, including how they operate and interact within the blockchain ecosystem.

## Steps
- Add a new ERC20 contract in the corresponding directory.

### PR DESCRIPTION
**Pull request by coxmars**
# 📝 Implement ERC20 Contract and Tests

## 🛠️ Issue
- Closes #26

## 📖 Description
This Pull Request implements a standard ERC20 smart contract with minting and burning functionalities, alongside comprehensive test cases to validate its behavior. The contract, named `MyToken`, follows the OpenZeppelin ERC20 structure and includes the following features:

1. **ERC20 Token Contract:**
   - A constructor to initialize the token's `name`, `symbol`, and `owner`.
   - Minting (`mint`) and burning (`burn`) functionalities:
     - Minting is restricted to the contract owner.
     - Burning allows token holders to reduce their own balances.
   - Balance management and standard transfer functionality using OpenZeppelin's ERC20 component.

2. **Tests:**
   - Tests for minting and burning tokens (`test_mint_and_burn`):
     - Ensures only the owner can mint tokens.
     - Validates token burning and balance updates.
   - Tests for token transfers (`test_transfer`):
     - Confirms correct token balance updates between users after transfers.
   - Tests for `approve` and `transfer_from` functionality (`test_approve_and_transfer_from`):
     - Verifies approval logic and token transfers on behalf of other users.

The tests use the `snforge_std` library to simulate different caller contexts (e.g., deploying contracts, emulating owner or user addresses) and validate the expected contract behavior.

## 🖼️ Screenshots (if applicable)

image

### CODE REVIEW

**Comment by danielcdz** [comment]
can you add a .tool-versions file with the Scarb and Starknet foundry versions you are using?

**Comment by danielcdz** [comment]
please rename the directory name from erc20 to simple_erc20

**Comment by coxmars** [comment]
@danielcdz comments applied 🫡

**Review by danielcdz — APPROVED** [review]
LGTM

**Pull request merged**
