### PR TITLE
Add Cairo script that calculates the fibonacci of a given number

### LINKED ISSUE #30: Fibonacci in Cairo
## Description
- Create a script in Cairo that calculates the Fibonacci of a given number.

## Steps
- Add the new script in the scripts directory.

### PR DESCRIPTION
**Pull request by aradix16**
Closes #30 

Added recursive and iterative way of calculating fibonacci. I think it can be interesting to get the two approaches. 

Note: Doesn't deal with overflow to keep the code simple, but can implement it if needed.

### CODE REVIEW

**Review by danielcdz — COMMENTED** [review]
Awesome job! love the comment about complexity, can you just add a .tool-versions file with the Scarb version you are using?

**Comment by danielcdz** [comment]
you can now set this as ready for review it lgtm

**Comment by aradix16** [comment]
thanks for your feedback! 
I've added the .tool-versions file i hope everything is ok.

**Review by danielcdz — APPROVED** [review]
LGTM

**Pull request merged**
