### PR TITLE
Adding hello world contract

### PR DESCRIPTION
**Pull request by Gerson2102**
This PR is adding the bases of a hello world contract for learning purposes. Solves #19.

### CODE REVIEW

**Comment by Gerson2102** [comment]
When I run `snforge test` it throws this:

```console
error[E0002]: Method `write` could not be called on type `core::starknet::storage::storage_base::StorageBase::<core::byte_array::ByteArray>`.
Candidate `StoragePointerWriteAccess::write` inference failed with: Trait has no implementation in context: core::starknet::storage::StoragePointerWriteAccess::<core::starknet::storage::storage_base::StorageBase::<core::byte_array::ByteArray>>.
 --> /root/stark-cairo-nodes/cairo/scripts/hello_world/src/hello_world.cairo:18:30
            self.stored_data.write("Hello world!")
```

**Comment by Gerson2102** [comment]
The test is failing. And I dont know why.

**Comment by danielcdz** [comment]
Try using felt252 to handle the string instead of a ByteArray

**Comment by Gerson2102** [comment]
Still throwing the same error. Weird asf.

**Comment by danielcdz** [comment]
Hmm ok I'll get your branch into my machine and check, for the moment I suggest researching in other repos how the thread bytearrays it seems that maybe we are missing an import or something like that

**Comment by Gerson2102** [comment]
```console

[FAIL] hello_world_integrationtest::test_contract::test_get_hello_world

Failure data:
    "Failed to get contract artifact for name = Hello."

Running 0 test(s) from src/
Tests: 0 passed, 1 failed, 0 skipped, 0 ignored, 0 filtered out

Failures:
    hello_world_integrationtest::test_contract::test_get_hello_world

```

**Comment by danielcdz** [comment]
@Gerson2102 can you add screenshots of the scarb build and snforge test result commands?

**Comment by Gerson2102** [comment]
`scarb build`

image

`snforge test`

image

Another weird thing that is happening, is the branches. If I go to scripts I'm in `hello-world-contract` if i go to hello_world I'm in main.

**Comment by danielcdz** [comment]
@Gerson2102 this happens because if you used `scarb init` to start the development this creates a new git repository, to solve this go to hello-world-contract and run `rm -r .git`

**Comment by Gerson2102** [comment]
Got it. Fixed it.

**Pull request merged**
